### ISSUE TITLE
Customize Stylesheet Extensions

### ISSUE THREAD

**Issue by ismaelr-philosit** [Philos-IT/custom-components-upp#7]
- [x] Create a new stylesheet extension
- [x] Customize and upload the CSS files for the new extension

**Comment by adarsh-philosit** [comment]
First implementation completed. 
Github Repository created for Custom Stylesheet extesnion.
Extension assigned to the active experience.
Changes made and reflected in the storefront Article Component.

**Comment by adarsh-philosit** [comment]
Githb repo for Custom Stylesheet extension can be seen here: https://github.com/Philos-IT/PWA-styling-coockbook-Extension
